---
- hosts: localhost

  tasks:
    - name: ovh_create
      include_tasks: ovh_create.yml
      with_items: "{{ ovh_instances }}"

    - name: ovh_delete
      include_tasks: ovh_delete.yml
      with_items: "{{ ovh_instances }}"